source 'https://github.com/CocoaPods/Specs.git'
include_official_source!

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'WasteSorting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WasteSorting
  pod 'ALCameraViewController'
  pod 'SwiftIconFont'
  pod 'YNSearch'

end
