source 'https://github.com/CocoaPods/Specs.git'

if respond_to? :include_official_source
  include_official_source!
end

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'WasteSorting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WasteSorting
  pod 'ALCameraViewController', :git => 'https://github.com/cxjwin/ALCameraViewController.git', :branch => 'master'
  pod 'SwiftIconFont', :git => 'https://github.com/cxjwin/SwiftIconFont.git', :branch => 'master'
  pod 'YNSearch'

end
